#!/usr/bin/env python

import ROOT as root
from helpers import *
root.gROOT.SetBatch(True)

if __name__ == "__main__":

  cuts = ""

  #cuts += "*( iBestMatch >= 0 && nMatchedTracks == 1)" # matching in analyzer

  # matching debug
  #cuts += "*(sqrt(pow(xWC-23.75,2)+pow(yWC-0.2,2)) < 11.93)" # wc track in flange
  #cuts += "*(trackXFrontTPC > -50. && trackXFrontTPC < -10. && trackYFrontTPC > 390. && trackYFrontTPC < 430.)" # TPC track in flange
  #cuts += "*(trackMatchLowestZ < 2.)" # matching
  #cuts += "*(fabs(trackMatchDeltaY) < 5.)" # matching
  #cuts += "*((!isMC && (trackMatchDeltaX < 6. && trackMatchDeltaX > -4.)) || (isMC && (fabs(trackMatchDeltaX) < 5.)))" # matching
  #cuts += "*(trackMatchDeltaAngle*180/pi < 10.)" # matching
  ###
  ###
  cutGoodBeamline = "(triggerIsBeam == 1 && BITrigger > 0 && BITriggerMatched > 0 && nBeamTracks > 0 && nBeamMom > 0)"
  secTrkCuts = "*(trackStartDistToPrimTrkEnd < 2.)"
  #weightStr = "pzWeight"+cuts
  weightStr = "1"+cuts

  weightStrTrackMatch = "1"+cuts#+"*(trackMatchLowestZ < 2.)"

  #nData = 224281.0
  logy = False

  c = root.TCanvas()
  NMAX=10000000000
  #NMAX=100
  fileConfigs = [
    #{
    #  'fn': "piAbsSelector_run5387_v3.root",
    #  'name': "run5387",
    #  'title': "Run 5387: 1 GeV/c",
    #  'caption': "Run 5387: 1 GeV/c",
    #  'color': root.kBlue-7,
    #  'cuts': "*"+cutGoodBeamline,
    #},
    {
      'fn': "piAbsSelector_run5432_v3.root",
      'name': "run5432",
      'title': "Run 5432: 2 GeV/c",
      'caption': "Run 5432: 2 GeV/c",
      'color': root.kGreen+3,
      'cuts': "*"+cutGoodBeamline,
    },
    #{
    #  'fn': "piAbsSelector_run5145_v3.root",
    #  'name': "run5145",
    #  'title': "Run 5145: 7 GeV/c",
    #  'caption': "Run 5145: 7 GeV/c",
    #  'color': root.kOrange-3,
    #  'cuts': "*"+cutGoodBeamline,
    #},
    {
      'fn': "piAbsSelector_mcc11_flf_2GeV.root",
      'name': "mcc11_flf_2GeV",
      'title': "MCC11 2 GeV FLF",
      'caption': "MCC11 2 GeV FLF",
      'color': root.kBlack,
      'isData': False,
    },
  ]

  histConfigs = [
    {
      'name': "nWC",
      'xtitle': "X Position of WC track projection to TPC [cm]",
      'ytitle': "Events / bin",
      'binning': [50,-100,50],
      'var': "xWC",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "xWC",
      'xtitle': "X Position of WC track projection to TPC [cm]",
      'ytitle': "Events / bin",
      'binning': [400,-200,200],
      'var': "xWC",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "yWC",
      'xtitle': "Y Position of WC track projection to TPC [cm]",
      'ytitle': "Events / bin",
      'binning': [300,300,600],
      'var': "yWC",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "pWC",
      'xtitle': "Momentum from WC [MeV/c]",
      'ytitle': "Events / bin",
      'binning': [120,0,12],
      'var': "pWC",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
      'printIntegral': True,
    },
#    {
#      'name': "pWC_NoCuts",
#      'xtitle': "Momentum from WC [MeV/c]",
#      'ytitle': "Events / bin",
#      'binning': [60,300,1500],
#      'var': "pWC",
#      'cuts': "pzWeight*(isMC || (firstTOF > -100))",
#      #'normalize': True,
#      'logy': logy,
#      'printIntegral': True,
#    },
#    {
#      'name': "kinWC",
#      'xtitle': "Kinetic Energy at WC [MeV/c] (m=m_{#pi^{#pm}})",
#      'ytitle': "Events / bin",
#      'binning': [100,0,2000],
#      'var': "kinWC",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "kinWCInTPC",
#      'xtitle': "Kinetic Energy at TPC [MeV/c] (m=m_{#pi^{#pm}})",
#      'ytitle': "Events / bin",
#      'binning': [100,0,2000],
#      'var': "kinWCInTPC",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
    {
      'name': "phiWC",
      'xtitle': "WC track #phi [deg]",
      'ytitle': "Events / bin",
      'binning': [360,-180,180],
      'var': "phiWC*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "thetaWC",
      'xtitle': "WC track #theta [deg]",
      'ytitle': "Events / bin",
      'binning': [40,0,10],
      'var': "thetaWC*180/pi",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
#    {
#      'name': "thetaxzWC",
#      'xtitle': "WC track #theta_{xz} [deg]",
#      'ytitle': "Events / bin",
#      'binning': [100,-10,10],
#      'var': "(atan(tan(thetaWC)*cos(phiWC)))*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "thetayzWC",
#      'xtitle': "WC track #theta_{yz} [deg]",
#      'ytitle': "Events / bin",
#      'binning': [100,-5,5],
#      'var': "(asin(tan(thetaWC)*sin(phiWC)))*180/pi",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "sinthetayz",
#      'xtitle': "WC Track sin(#theta_{yz})",
#      'ytitle': "Tracks / bin",
#      'binning': [80,-0.1,0.1],
#      'var': "sin(thetaWC)*sin(phiWC)",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
    {
      'name': "primTrkStartZ",
      'xtitle': "Primary TPC Track Start Z [cm]",
      'ytitle': "Events / bin",
      'binning': [60,-3,3],
      'var': "primTrkStartZ",
      'cuts': weightStr,
      #'normalize': True,
      'logy': False,
    },
    {
      'name': "primTrkStartZ_Logy",
      'xtitle': "Primary TPC Track Start Z [cm]",
      'ytitle': "Events / bin",
      'binning': [60,-10,10],
      'var': "primTrkStartZ",
      'cuts': weightStr,
      #'normalize': True,
      'logy': True,
    },
    {
      'name': "nTracks",
      'xtitle': "Number of TPC Tracks / Event",
      'ytitle': "Events / bin",
      'binning': [100,0,200],
      'var': "nTracks",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "nTracksInFirstZ2",
      'xtitle': "Number of TPC Tracks in first 2 cm / Event",
      'ytitle': "Events / bin",
      'binning': [16,0,15],
      'var': "nTracksInFirstZ[2]",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "nTracksInFirstZ14",
      'xtitle': "Number of TPC Tracks in first 14 cm / Event",
      'ytitle': "Events / bin",
      'binning': [16,0,15],
      'var': "nTracksInFirstZ[14]",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "nTracksLengthLt5",
      'xtitle': "Number of TPC Tracks with length < 5 cm / Event",
      'ytitle': "Events / bin",
      'binning': [16,0,15],
      'var': "nTracksLengthLt[5]",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "nMatchedTracks",
      'xtitle': "Number of TPC/WC Track Matches / Event",
      'ytitle': "Events / bin",
      'binning': [11,0,10],
      'var': "nMatchedTracks",
      'cuts': weightStr,
      #'normalize': True,
      'logy': True,
    },
    {
      'name': "trackMatchDeltaX",
      'xtitle': "TPC / WC Track #Delta x at TPC Front [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [40,-10,10],
      #'var': "trackMatchDeltaX[iBestMatch]",
      #'cuts': "(iBestMatch >= 0)*"+weightStr,
      'var': "trackMatchDeltaX",
      'cuts': weightStrTrackMatch,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchDeltaX_wide",
      'xtitle': "TPC / WC Track #Delta x at TPC Front [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [100,-500,500],
      #'var': "trackMatchDeltaX[iBestMatch]",
      #'cuts': "(iBestMatch >= 0)*"+weightStr,
      'var': "trackMatchDeltaX",
      'cuts': weightStrTrackMatch,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchDeltaY",
      'xtitle': "TPC / WC Track #Delta y at TPC Front [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [40,-10,10],
      #'var': "trackMatchDeltaY[iBestMatch]",
      #'cuts': "(iBestMatch >= 0)*"+weightStr,
      'var': "trackMatchDeltaY",
      'cuts': weightStrTrackMatch,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchDeltaY_wide",
      'xtitle': "TPC / WC Track #Delta y at TPC Front [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [100,-500,500],
      #'var': "trackMatchDeltaY[iBestMatch]",
      #'cuts': "(iBestMatch >= 0)*"+weightStr,
      'var': "trackMatchDeltaY",
      'cuts': weightStrTrackMatch,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchDeltaAngle",
      'xtitle': "TPC / WC Track #Delta #alpha [deg]",
      'ytitle': "TPC Tracks / bin",
      #'binning': [90,0,180],
      'binning': [40,0,20],
      #'var': "trackMatchDeltaAngle[iBestMatch]*180/pi",
      #'cuts': "(iBestMatch >= 0)*"+weightStr,
      'var': "trackMatchDeltaAngle*180/pi",
      'cuts': weightStrTrackMatch,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchDeltaAngle_wide",
      'xtitle': "TPC / WC Track #Delta #alpha [deg]",
      'ytitle': "TPC Tracks / bin",
      'binning': [90,0,180],
      #'binning': [20,0,20],
      #'var': "trackMatchDeltaAngle[iBestMatch]*180/pi",
      #'cuts': "(iBestMatch >= 0)*"+weightStr,
      'var': "trackMatchDeltaAngle*180/pi",
      'cuts': weightStrTrackMatch,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackXFrontTPC",
      'xtitle': "X of TPC Track Projection to TPC Front [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [100,-50,0],
      'var': "trackXFrontTPC",
      'cuts': weightStrTrackMatch,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackYFrontTPC",
      'xtitle': "Y of TPC Track Projection to TPC Front [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [100,340,500],
      'var': "trackYFrontTPC",
      'cuts': weightStrTrackMatch,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackMatchLowestZ",
      'xtitle': "TPC Track Start Z [cm]",
      'ytitle': "TPC Tracks / bin",
      'binning': [50,-5,20],
      'var': "trackMatchLowestZ",
      'cuts': weightStrTrackMatch,
      #'normalize': True,
      'logy': logy,
    },
#    {
#      'name': "nTOFs",
#      'xtitle': "Number of TOF Objects",
#      'ytitle': "Events / bin",
#      'binning': [11,0,10],
#      'var': "nTOFs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "TOFs",
#      'xtitle': "TOF [ns]",
#      'ytitle': "TOFs / bin",
#      'binning': [100,0,100],
#      'var': "TOFs",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
#    {
#      'name': "firstTOF",
#      'xtitle': "TOF [ns]",
#      'ytitle': "Events / bin",
#      'binning': [100,0,100],
#      'var': "firstTOF",
#      'cuts': weightStr,
#      #'normalize': True,
#      'logy': logy,
#    },
    {
      'name': "trackStartX",
      'xtitle': "TPC Track Start X [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-400,400],
      'var': "trackStartX",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackStartY",
      'xtitle': "TPC Track Start Y [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-5,650],
      'var': "trackStartY",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackStartZ",
      'xtitle': "TPC Track Start Z [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-5,25],
      'var': "trackStartZ",
      'cuts': weightStr,
      #'normalize': True,
      'logy': False,
    },
    {
      'name': "trackStartZ_Logy",
      'xtitle': "TPC Track Start Z [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-5,25],
      'var': "trackStartZ",
      'cuts': weightStr,
      #'normalize': True,
      'logy': True,
    },
    {
      'name': "trackStartZ_wide",
      'xtitle': "TPC Track Start Z [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-25,725],
      'var': "trackStartZ",
      'cuts': weightStr,
      #'normalize': True,
      'logy': False,
    },
    {
      'name': "trackStartZ_wide_Logy",
      'xtitle': "TPC Track Start Z [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-25,725],
      'var': "trackStartZ",
      'cuts': weightStr,
      #'normalize': True,
      'logy': True,
    },
    {
      'name': "trackEndX",
      'xtitle': "TPC Track End X [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-400,400],
      'var': "trackEndX",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackEndY",
      'xtitle': "TPC Track End Y [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-5,650],
      'var': "trackEndY",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackEndZ",
      'xtitle': "TPC Track End Z [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-25,725],
      'var': "trackEndZ",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackLength",
      'xtitle': "TPC Track Length [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-0,1000],
      'var': "trackLength",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackLength_logy",
      'xtitle': "TPC Track Length [cm]",
      'ytitle': "Tracks / bin",
      'binning': [200,-0,1000],
      'var': "trackLength",
      'cuts': weightStr,
      #'normalize': True,
      'logy': not logy,
    },
    #{
    #  'name': "trackCaloKin",
    #  'xtitle': "TPC Calo Estimate of KE [MeV]",
    #  'ytitle': "Tracks / bin",
    #  'binning': [50,0,2500],
    #  'var': "trackCaloKin",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackLLHPion",
    #  'xtitle': "TPC Track Pion -logLH",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,5000],
    #  'var': "-trackLLHPion",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackLLHProton",
    #  'xtitle': "TPC Track Proton -logLH",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,5000],
    #  'var': "-trackLLHProton",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackLLHMuon",
    #  'xtitle': "TPC Track Muon -logLH",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,5000],
    #  'var': "-trackLLHMuon",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackLLHKaon",
    #  'xtitle': "TPC Track Kaon -logLH",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,5000],
    #  'var': "-trackLLHKaon",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackPIDA",
    #  'xtitle': "TPC Track PIDA",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,50],
    #  'var': "trackPIDA",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackLLR",
    #  'xtitle': "TPC Track Pion/Proton LLHR",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,-300,1000],
    #  'var': "trackLLHPion-trackLLHProton",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "trackLLRInt",
    #  'xtitle': "TPC Track Pion/Proton LLHR",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,-300,1000],
    #  'var': "primTrkLLHPion-primTrkLLHProton",
    #  'cuts': weightStr,
    #  #'logy': logy,
    #  'normalize': True,
    #  'integral': True
    #},
    #{
    #  'name': "primTrkLLHPion",
    #  'xtitle': "Primary TPC Track Pion -logLH",
    #  'ytitle': "Events / bin",
    #  'binning': [100,0,5000],
    #  'var': "-primTrkLLHPion",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "primTrkLLHProton",
    #  'xtitle': "Primary TPC Track Proton -logLH",
    #  'ytitle': "Events / bin",
    #  'binning': [100,0,5000],
    #  'var': "-primTrkLLHProton",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "primTrkLLHMuon",
    #  'xtitle': "Primary TPC Track Muon -logLH",
    #  'ytitle': "Events / bin",
    #  'binning': [100,0,5000],
    #  'var': "-primTrkLLHMuon",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "primTrkLLHKaon",
    #  'xtitle': "Primary TPC Track Kaon -logLH",
    #  'ytitle': "Events / bin",
    #  'binning': [100,0,5000],
    #  'var': "-primTrkLLHKaon",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "primTrkLLR",
    #  'xtitle': "Primary TPC Track Pion/Proton LLHR",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,-300,1000],
    #  'var': "primTrkLLHPion-primTrkLLHProton",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "primTrkLLRInt",
    #  'xtitle': "Primary TPC Track Pion/Proton LLHR",
    #  'ytitle': "Efficiency for Cut >= X",
    #  'binning': [100,-300,1000],
    #  'var': "primTrkLLHPion-primTrkLLHProton",
    #  'cuts': weightStr,
    #  #'logy': logy,
    #  'normalize': True,
    #  'integral': True
    #},
    #{
    #  'name': "primTrkLLRKP",
    #  'xtitle': "Primary TPC Track Kaon/Proton LLHR",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,-300,1000],
    #  'var': "primTrkLLHKaon-primTrkLLHProton",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "primTrkLLRKPInt",
    #  'xtitle': "Primary TPC Track Kaon/Proton LLHR",
    #  'ytitle': "Efficiency for Cut >= X",
    #  'binning': [100,-300,1000],
    #  'var': "primTrkLLHKaon-primTrkLLHProton",
    #  'cuts': weightStr,
    #  #'logy': logy,
    #  'normalize': True,
    #  'integral': True
    #},
    #{
    #  'name': "primTrkPIDA",
    #  'xtitle': "Primary TPC Track PIDA",
    #  'ytitle': "Events / bin",
    #  'binning': [100,0,50],
    #  'var': "primTrkPIDA",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "trackStartDistToPrimTrkEnd",
      'xtitle': "TPC Track Start Distance to Primary End [cm]",
      'ytitle': "Tracks / bin",
      #'binning': [40,0,20],
      'binning': [160,0,80],
      'var': "trackStartDistToPrimTrkEnd",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "trackEndDistToPrimTrkEnd",
      'xtitle': "TPC Track End Distance to Primary End [cm]",
      'ytitle': "Tracks / bin",
      #'binning': [40,0,20],
      'binning': [160,0,80],
      'var': "trackEndDistToPrimTrkEnd",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "secTrkLength",
      'xtitle': "Secondary TPC Track Length [cm]",
      'ytitle': "Tracks / bin",
      'binning': [100,-10,100],
      'var': "trackLength",
      'cuts': weightStr+secTrkCuts,
      #'normalize': True,
      'logy': logy,
    },
    #{
    #  'name': "secTrkCaloKin",
    #  'xtitle': "Secondary Track Calo Estimate of KE [MeV]",
    #  'ytitle': "Tracks / bin",
    #  'binning': [50,0,2500],
    #  'var': "trackCaloKin",
    #  'cuts': weightStr+secTrkCuts,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "secTrkLLHPion",
    #  'xtitle': "Secondary TPC Track Pion -logLH",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,5000],
    #  'var': "-trackLLHPion",
    #  'cuts': weightStr+secTrkCuts,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "secTrkLLHProton",
    #  'xtitle': "Secondary TPC Track Proton -logLH",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,5000],
    #  'var': "-trackLLHProton",
    #  'cuts': weightStr+secTrkCuts,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "secTrkLLHMuon",
    #  'xtitle': "Secondary TPC Track Muon -logLH",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,5000],
    #  'var': "-trackLLHMuon",
    #  'cuts': weightStr+secTrkCuts,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "secTrkLLHKaon",
    #  'xtitle': "Secondary TPC Track Kaon -logLH",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,5000],
    #  'var': "-trackLLHKaon",
    #  'cuts': weightStr+secTrkCuts,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "secTrkStartZ",
      'xtitle': "Secondary TPC Track Start z [cm]",
      'ytitle': "Tracks / bin",
      'binning': [120,-10,110],
      'var': "trackStartZ",
      'cuts': weightStr+secTrkCuts,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "secTrkLLR",
      'xtitle': "Secondary TPC Track Pion/Proton LLHR",
      'ytitle': "Tracks / bin",
      'binning': [100,-300,1000],
      'var': "trackLLHPion-trackLLHProton",
      'cuts': weightStr+secTrkCuts,
      #'normalize': True,
      'logy': logy,
    },
    #{
    #  'name': "secTrkLLRInt",
    #  'xtitle': "Secondary TPC Track Pion/Proton LLHR",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,-300,1000],
    #  'var': "primTrkLLHPion-primTrkLLHProton",
    #  'cuts': weightStr+secTrkCuts,
    #  #'logy': logy,
    #  'normalize': True,
    #  'integral': True
    #},
    #{
    #  'name': "secTrkPIDA",
    #  'xtitle': "Secondary TPC Track PIDA",
    #  'ytitle': "Tracks / bin",
    #  'binning': [100,0,50],
    #  'var': "trackPIDA",
    #  'cuts': weightStr+secTrkCuts,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "primTrkLength",
      'xtitle': "Primary TPC Track Length [cm]",
      'ytitle': "Events / bin",
      'binning': [100,0,100],
      'var': "primTrkLength",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkdEdxs",
      'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
      'ytitle': "Events / bin",
      'binning': [200,0,50],
      'var': "primTrkdEdxs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    #{
    #  'name': "primTrkdEdxsFidCut",
    #  'xtitle': "Primary TPC Track dE/dx [MeV/cm]",
    #  'ytitle': "Events / bin",
    #  'binning': [200,0,50],
    #  'var': "primTrkdEdxs",
    #  'cuts': weightStr+"*primTrkInFids",
    #  #'normalize': True,
    #  'logy': logy,
    #},
    #{
    #  'name': "primTrkResRanges",
    #  'xtitle': "Primary TPC Track Residual Range [cm]",
    #  'ytitle': "Events / bin",
    #  'binning': [200,0,100],
    #  'var': "primTrkResRanges",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "primTrkEndKin",
      'xtitle': "Primary TPC Track End Kinetic Energy [MeV]",
      'ytitle': "Events / bin",
      'binning': [50,0,1000],
      'var': "primTrkEndKin",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    #{
    #  'name': "primTrkEndKinFid",
    #  'xtitle': "Primary TPC Track End Kinetic Energy [MeV]",
    #  'ytitle': "Events / bin",
    #  'binning': [50,0,1000],
    #  'var': "primTrkEndKinFid",
    #  'cuts': weightStr,
    #  #'normalize': True,
    #  'logy': logy,
    #},
    {
      'name': "primTrkKins",
      'xtitle': "Primary TPC Track Hit Kinetic Energy [MeV]",
      'ytitle': "Events / bin",
      'binning': [100,0,1000],
      'var': "primTrkKins",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkKinInteract",
      'xtitle': "Primary TPC Track Interaction Kinetic Energy [MeV]",
      'ytitle': "Events / bin",
      'binning': [100,0,1000],
      'var': "primTrkKinInteract",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
    {
      'name': "primTrkZs",
      'xtitle': "Primary TPC Track Hit Z coordinates [cm]",
      'ytitle': "Events / bin",
      'binning': [80,-10,10],
      'var': "primTrkZs",
      'cuts': weightStr,
      #'normalize': True,
      'logy': logy,
    },
  ]

  #for i in reversed(range(len(histConfigs))):
  #  if histConfigs[i]['name'] != "pzWC":
  #  #if histConfigs[i]['name'] != "zWC4Hit":
  #    histConfigs.pop(i)

  #plotManyFilesOnePlot(fileConfigs,histConfigs,c,"PiAbsSelector/tree",outPrefix="DataMC_",nMax=NMAX)
  fileConfigMCs = copy.deepcopy(fileConfigs)
  fileConfigDatas = []
  for i in reversed(range(len(fileConfigMCs))):
    if 'isData' in fileConfigMCs[i] and fileConfigMCs[i]['isData']:
      fileConfigDatas.append(fileConfigMCs.pop(i))
  DataMCStack(fileConfigDatas,fileConfigMCs,histConfigs,c,"PiAbsSelector/tree",outPrefix="DataMC_",nMax=NMAX)
  DataMCCategoryStack(fileConfigDatas,fileConfigMCs,histConfigs,c,"PiAbsSelector/tree",
                outPrefix="DataMC_",nMax=NMAX,
                catConfigs=TRUECATEGORYFEWERCONFIGS
             )

  histConfigs = [
    #{
    #  'name': "thetayzWCVthetaxzWC",
    #  'xtitle': "WC track #theta_{xz} [deg]",
    #  'ytitle': "WC track #theta_{yz} [deg]",
    #  'binning': [40,-10,10,40,-10,10],
    #  'var': "(asin(sin(thetaWC)*sin(phiWC)))*180/pi:(atan(tan(thetaWC)*cos(phiWC)))*180/pi",
    #  'cuts': "",
    #  #'normalize': True,
    #  #'logy': logy,
    #},
    #{
    #  'name': "xWCVthetaxzWC",
    #  'xtitle': "WC track #theta_{xz} [deg]",
    #  'ytitle': "X of WC track projected to front of TPC [cm]",
    #  'binning': [40,-10,10,40,0,75],
    #  'var': "xWC:(atan(tan(thetaWC)*cos(phiWC)))*180/pi",
    #  'cuts': "",
    #  #'normalize': True,
    #  #'logy': logy,
    #},
    #{
    #  'name': "xWCVxWC4Hit",
    #  'xtitle': "X of WC4 Hit [cm]",
    #  'ytitle': "X of WC track projected to front of TPC [cm]",
    #  'binning': [50,0,50,40,0,75],
    #  'var': "xWC:xWC4Hit",
    #  'cuts': "",
    #  #'normalize': True,
    #  #'logy': logy,
    #},
#    {
#      'name': "primTrkLLRVPIDA",
#      'xtitle': "Primary TPC Track PIDA",
#      'ytitle': "Primary TPC Track Pion/Proton LLHR",
#      'binning': [100,0,50,100,-300,1000],
#      'var': "primTrkLLHPion-primTrkLLHProton:primTrkPIDA",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkLLRVpWC",
#      'xtitle': "WC Momentum [MeV/c]",
#      'ytitle': "Primary TPC Track Pion/Proton LLHR",
#      'binning': [100,0,1500,100,-300,1000],
#      'var': "primTrkLLHPion-primTrkLLHProton:pWC",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkLLRKPVpWC",
#      'xtitle': "WC Momentum [MeV/c]",
#      'ytitle': "Primary TPC Track Kaon/Proton LLHR",
#      'binning': [100,0,1500,100,-300,1000],
#      'var': "primTrkLLHKaon-primTrkLLHProton:pWC",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkPIDAPVpWC",
#      'xtitle': "WC Momentum [MeV/c]",
#      'ytitle': "Primary TPC Track PIDA",
#      'binning': [100,0,1500,100,0,50],
#      'var': "primTrkPIDA:pWC",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkLengthPVpWC",
#      'xtitle': "WC Momentum [MeV/c]",
#      'ytitle': "Primary TPC Track Length [cm]",
#      'binning': [100,0,1500,100,0,100],
#      'var': "primTrkLength:pWC",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkdEdxVRange",
#      'xtitle': "Primary Track Hit Residual Range [cm]",
#      'ytitle': "Primary Track Hit dE/dx [MeV/cm]",
#      'binning': [100,0,100,100,0,50],
#      'var': "primTrkdEdxs:primTrkResRanges",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "primTrkdEdxVRangeFidCut",
#      'xtitle': "Primary Track Hit Residual Range [cm]",
#      'ytitle': "Primary Track Hit dE/dx [MeV/cm]",
#      'binning': [100,0,100,100,0,50],
#      'var': "primTrkdEdxs:primTrkResRanges",
#      'cuts': weightStr+"*primTrkInFids",
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "firstTOFVnTOFs",
#      'xtitle': "nTOFs",
#      'ytitle': "First TOF [ns]",
#      'binning': [11,0,10,100,0,50],
#      'var': "firstTOF:nTOFs",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "yWCVxWC",
#      'xtitle': "X Position of WC track projection to TPC [cm]",
#      'ytitle': "Y Position of WC track projection to TPC [cm]",
#      'binning': [40,0,40,40,-20,20],
#      'var': "yWC:xWC",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "trackYFrontTPCVtrackXFrontTPC",
#      'xtitle': "X of TPC Track Projection to TPC Front [cm]",
#      'ytitle': "Y of TPC Track Projection to TPC Front [cm]",
#      'binning': [40,0,40,40,-20,20],
#      'var': "trackYFrontTPC:trackXFrontTPC",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
    {
      'name': "trackLengthVtrackStartZ",
      'ytitle': "TPC Track Length [cm]",
      'xtitle': "TPC Track Start z [cm]",
      'binning': [25,-5,700,30,0,1000],
      'var': "trackLength:trackStartZ",
      'cuts': weightStr,
      #'normalize': True,
      #'logz': True,
    },
#    {
#      'name': "trackStartDistToPrimTrkEndVtrackStartZ",
#      'xtitle': "TPC Track Start z [cm]",
#      'ytitle': "TPC Track Start Distance to Primary End [cm]",
#      'binning': [25,0,100,20,0,80],
#      'var': "trackStartDistToPrimTrkEnd:trackStartZ",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
#    {
#      'name': "trackStartDistToPrimTrkEndVprimTrkEndZ",
#      'xtitle': "Primary TPC Track End z [cm]",
#      'ytitle': "TPC Track Start Distance to Primary End [cm]",
#      'binning': [25,0,100,20,0,80],
#      'var': "trackStartDistToPrimTrkEnd:primTrkEndZ",
#      'cuts': weightStr,
#      #'normalize': True,
#      #'logz': True,
#    },
    {
      'name': "trackYFrontTPCVtrackXFrontTPC",
      'xtitle': "X of TPC Track Projected to Z=0 [cm]",
      'ytitle': "Y of TPC Track Projected to Z=0 [cm]",
      'binning': [30,-60,0,30,300,500],
      'var': "trackYFrontTPC:trackXFrontTPC",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "trackYFrontTPCVtrackXFrontTPC_beamMatched",
      'xtitle': "X of TPC Track Projected to Z=0 [cm]",
      'ytitle': "Y of TPC Track Projected to Z=0 [cm]",
      'binning': [30,-60,0,30,300,500],
      'var': "trackYFrontTPC:trackXFrontTPC",
      'cuts': weightStr+"*(trackTrueIsBeam && trackTrueMotherID==0)",
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "trackYFrontTPCVtrackXFrontTPC_wide",
      'xtitle': "X of TPC Track Projected to Z=0 [cm]",
      'ytitle': "Y of TPC Track Projected to Z=0 [cm]",
      'binning': [100,-400,400,100,0,700],
      'var': "trackYFrontTPC:trackXFrontTPC",
      'cuts': weightStr,
      #'normalize': True,
      'logz': False,
    },
    {
      'name': "trackYFrontTPCVtrackXFrontTPC_wide_beamMatched",
      'xtitle': "X of TPC Track Projected to Z=0 [cm]",
      'ytitle': "Y of TPC Track Projected to Z=0 [cm]",
      'binning': [100,-400,400,100,0,700],
      'var': "trackYFrontTPC:trackXFrontTPC",
      'cuts': weightStr+"*(trackTrueIsBeam && trackTrueMotherID==0)",
      #'normalize': True,
      'logz': False,
    },
  ]

  plotOneHistOnePlot(fileConfigs,histConfigs,c,"PiAbsSelector/tree",outPrefix="DataMC_",nMax=NMAX)

